global:
  scrape_interval: 15s

rule_files:
  - "rules/alerts.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node_exporter
    static_configs:
      - targets:
          - 10.0.1.189 #idm9-target1
          - 10.0.4.14 # idm10-target2
          - 10.0.0.223 #idm8-monitoring
